INFO 2025-07-29 07:13:30,880 autoreload 2460 140185064341760 Watching for file changes with StatReloader
ERROR 2025-07-29 07:13:38,128 log 2460 140184788305600 Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = middleware_method(
        request, callback, callback_args, callback_kwargs
    )
  File "/workspace/noctisview/middleware.py", line 74, in process_view
    csrf_middleware = CsrfViewMiddleware()
TypeError: MiddlewareMixin.__init__() missing 1 required positional argument: 'get_response'
ERROR 2025-07-29 07:13:38,128 basehttp 2460 140184788305600 "HEAD / HTTP/1.1" 500 0
ERROR 2025-07-29 07:13:42,829 log 2460 140184788305600 Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = middleware_method(
        request, callback, callback_args, callback_kwargs
    )
  File "/workspace/noctisview/middleware.py", line 74, in process_view
    csrf_middleware = CsrfViewMiddleware()
TypeError: MiddlewareMixin.__init__() missing 1 required positional argument: 'get_response'
ERROR 2025-07-29 07:13:42,830 basehttp 2460 140184788305600 "GET / HTTP/1.1" 500 62490
INFO 2025-07-29 07:14:01,667 autoreload 2899 140179492512000 Watching for file changes with StatReloader
ERROR 2025-07-29 07:14:06,723 log 2899 140179142604480 Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = middleware_method(
        request, callback, callback_args, callback_kwargs
    )
  File "/workspace/noctisview/middleware.py", line 74, in process_view
    csrf_middleware = CsrfViewMiddleware()
TypeError: MiddlewareMixin.__init__() missing 1 required positional argument: 'get_response'
ERROR 2025-07-29 07:14:06,724 basehttp 2899 140179142604480 "HEAD / HTTP/1.1" 500 0
INFO 2025-07-29 08:07:14,594 autoreload 2323 139880513061120 Watching for file changes with StatReloader
INFO 2025-07-29 08:07:22,611 basehttp 2323 139880169469632 "GET /admin/ HTTP/1.1" 302 0
ERROR 2025-07-29 12:10:19,338 exception 2564 140199739568384 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-07-29 12:10:19,380 log 2564 140199739568384 Bad Request: /viewer/api/upload/
ERROR 2025-07-29 12:10:43,648 exception 2634 140518907339008 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/workspace/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/workspace/venv/lib/python3.13/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-07-29 12:10:43,687 log 2634 140518907339008 Bad Request: /viewer/api/upload/
